
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pypackage_hello"
version = "0.1.0"
description = "A simple example package"
dependencies = [
    "requests",
    "scikit-learn",
]

[tool.setuptools.packages.find]
where = ["."]